// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-event-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/data.ts
var EVENT = {
  name: "AVISHKAAR Season 4",
  organizer: "Aditya Institute of Technology and Management, Tekkali",
  tagline: "A 48-hour innovation marathon that challenges bright minds to turn bold ideas into real-world solutions.",
  format: "Two phases: a 24-hour online hackathon and an on-campus 48-hour grand finale.",
  teamSize: "1-4 members per team",
  registrationFee: "Free \u2014 there is no registration fee",
  eligibility: "Students from all academic backgrounds and levels (undergraduate, graduate and postgraduate). Interdisciplinary teams are encouraged.",
  registrationUrl: "https://unstop.com/o/3C4O1aP?lb=O4B2h3r",
  prizes: ["1st place", "2nd place", "3rd place"]
};
var TRACKS = [
  "Digital Empowerment for Rural Communities",
  "Urban Mobility & Traffic Management",
  "Agriculture & Food Technology",
  "Medical & Health",
  "Waste Management & Recycling",
  "Renewable & Sustainable Energy",
  "Tourism & Travel",
  "Student Innovation (Open Theme)"
];
var FAQS = [
  {
    question: "Who can participate in AVISHKAAR Season 4?",
    answer: "Students from all academic backgrounds and levels can participate, including undergraduate, graduate and postgraduate students from various disciplines."
  },
  {
    question: "Can I participate in both Virtual and Physical Hackathon tracks?",
    answer: "No. Participants choose one track \u2014 either Virtual or Physical Hackathon \u2014 and cannot take part in both simultaneously."
  },
  {
    question: "How will pitching be conducted for the Virtual Hackathon?",
    answer: "Virtual pitching happens over online video conferencing. Teams present to judges via screen sharing and live demonstrations."
  },
  {
    question: "What tools can I use during the Virtual Hackathon?",
    answer: "Any programming languages, frameworks or tools. There are no restrictions on the technology stack."
  },
  {
    question: "What can the team size be?",
    answer: "Teams can have 1-4 members. Individual participation is allowed and teams cannot exceed 4 members."
  },
  {
    question: "Is security provided for our projects?",
    answer: "Yes. Adequate security measures and secure storage protect projects and equipment during the Physical Hackathon."
  },
  {
    question: "Are food and accommodation provided?",
    answer: "Food is provided during the hackathon. Accommodation can be arranged on request with prior notice to the organizing committee."
  },
  {
    question: "Can a team consist of students from different domains?",
    answer: "Yes. Interdisciplinary teams are encouraged so projects benefit from diverse perspectives."
  },
  {
    question: "Is there any registration fee?",
    answer: "No. Participation in AVISHKAAR Season 4 is free for all eligible participants."
  },
  {
    question: "What are the evaluation criteria?",
    answer: "Innovation, technical implementation, feasibility, presentation quality and potential impact. Detailed rubrics are shared with participants."
  },
  {
    question: "Will hardware support be available during the Physical Hackathon?",
    answer: "Yes. Basic hardware components and development boards are available, though teams may bring their own specialized hardware."
  },
  {
    question: "Do participants have to arrange their own travel?",
    answer: "Yes. Participants arrange their own travel. Travel reimbursement may be available for selected teams based on specific criteria."
  }
];
var CONTACTS = {
  email: "avishkaar@adityatekkali.edu.in",
  phones: [{ name: "S. Vinod Kumar", phone: "+91 9866854604" }],
  venue: "Aditya Institute of Technology and Management, Tekkali"
};

// src/lib/mcp/tools/get-event-overview.ts
var get_event_overview_default = defineTool({
  name: "get_event_overview",
  title: "Get event overview",
  description: "Get the public overview of the AVISHKAAR Season 4 hackathon: format, eligibility, team size, fee, prizes and the registration link.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(EVENT, null, 2) }],
    structuredContent: { event: EVENT }
  })
});

// src/lib/mcp/tools/list-tracks.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_tracks_default = defineTool2({
  name: "list_tracks",
  title: "List hackathon tracks",
  description: "List the public problem-statement tracks / themes teams can build for at AVISHKAAR Season 4.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: TRACKS.map((t, i) => `${i + 1}. ${t}`).join("\n") }],
    structuredContent: { tracks: TRACKS }
  })
});

// src/lib/mcp/tools/search-faqs.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var search_faqs_default = defineTool3({
  name: "search_faqs",
  title: "Search FAQs",
  description: "Search the public AVISHKAAR Season 4 FAQ. Omit the query to get every question and answer.",
  inputSchema: {
    query: z.string().trim().optional().describe("Optional keyword to filter FAQ questions and answers.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query?.toLowerCase();
    const results = q ? FAQS.filter(
      (f) => f.question.toLowerCase().includes(q) || f.answer.toLowerCase().includes(q)
    ) : FAQS;
    const text = results.length ? results.map((f) => `Q: ${f.question}
A: ${f.answer}`).join("\n\n") : `No FAQ entry matched "${query}".`;
    return { content: [{ type: "text", text }], structuredContent: { faqs: results } };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Get the public contact details for the AVISHKAAR Season 4 organizing team: email, phone and venue.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CONTACTS, null, 2) }],
    structuredContent: { contact: CONTACTS }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "fire-web-revival",
  title: "Fire Web Revival",
  version: "0.1.0",
  instructions: "Public tools for the AVISHKAAR Season 4 hackathon site. Use `get_event_overview` for dates, format, eligibility and registration, `list_tracks` for the problem-statement themes, `search_faqs` for participant questions, and `get_contact_info` for organizer contact details.",
  tools: [get_event_overview_default, list_tracks_default, search_faqs_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
